spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/feedbaker
    username: postgres
    password: pass
  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
# App Properties
app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000